export interface DevTool {
  name: string;
  slug: string;
  tagline: string;
  description: string;
  icon: string;
  category: string;
  pricing: "free" | "freemium" | "paid" | "open-source";
  platforms: string[];
  url: string;
  whyUse: string[];
  keyFeatures: string[];
  quickStart: string[];
  proTips: string[];
  alternatives: string[];
}

export const toolCategories = [
  { key: "editor", label: "Code Editor & IDE", icon: "💻" },
  { key: "terminal", label: "Terminal & Shell", icon: "🖥️" },
  { key: "git", label: "Git & Version Control", icon: "🔀" },
  { key: "api", label: "API & HTTP Testing", icon: "🔌" },
  { key: "database", label: "Database Tools", icon: "🗃️" },
  { key: "container", label: "Container & DevOps", icon: "🐳" },
  { key: "design", label: "Design & UI", icon: "🎨" },
  { key: "collab", label: "Collaboration & PM", icon: "🤝" },
  { key: "browser", label: "Browser & Dev Tools", icon: "🌐" },
  { key: "ai", label: "AI-Powered Tools", icon: "🤖" },
  { key: "productivity", label: "Productivity", icon: "⚡" },
  { key: "monitoring", label: "Monitoring & Logging", icon: "📊" },
  { key: "docs", label: "Documentation", icon: "📝" },
  { key: "testing", label: "Testing & QA", icon: "🧪" },
];

export const tools: DevTool[] = [
  // ─── CODE EDITOR & IDE ───
  {
    name: "VS Code",
    slug: "vscode",
    tagline: "Code Editor ที่ Dev ทั่วโลกใช้มากที่สุด",
    description: "Visual Studio Code เป็น editor ฟรีจาก Microsoft ที่มี extension มากมาย รองรับแทบทุกภาษา เบา เร็ว customize ได้เยอะ — ตัวเลือกอันดับ 1 ของ developer ส่วนใหญ่",
    icon: "📝",
    category: "editor",
    pricing: "free",
    platforms: ["Windows", "macOS", "Linux"],
    url: "https://code.visualstudio.com",
    whyUse: [
      "ฟรี 100% แต่ทรงพลังเหมือน IDE เต็มรูปแบบ",
      "Extension marketplace มีมากกว่า 40,000 ตัว ต้องการอะไรก็มีหมด",
      "IntelliSense ช่วย autocomplete โค้ดอัจฉริยะ",
      "Built-in terminal, Git, debugger ครบจบในตัวเดียว",
      "ชุมชนใหญ่มาก มีปัญหาอะไร Google แล้วเจอเลย",
    ],
    keyFeatures: [
      "IntelliSense — autocomplete + type checking อัตโนมัติ",
      "Integrated Terminal — เปิด terminal ได้เลยในตัว editor",
      "Git Integration — ดู diff, commit, push ได้โดยไม่ต้องออกจาก editor",
      "Extensions — Prettier, ESLint, GitLens, Thunder Client, Copilot",
      "Multi-cursor editing — แก้หลายจุดพร้อมกัน",
      "Remote Development — เขียนโค้ดบน server ผ่าน SSH",
      "Workspace settings — ตั้งค่าแยกตามโปรเจกต์",
    ],
    quickStart: [
      "ดาวน์โหลดจาก code.visualstudio.com แล้วติดตั้ง",
      "เปิดโฟลเดอร์โปรเจกต์: File → Open Folder",
      "ติดตั้ง extension จำเป็น: Prettier, ESLint, GitLens",
      "เรียนรู้ Shortcuts: Cmd+P (ค้นไฟล์), Cmd+Shift+P (Command Palette)",
      "ตั้งค่า Auto Save, Format on Save ให้ชีวิตง่ายขึ้น",
    ],
    proTips: [
      "Cmd+D เลือกคำเดียวกันทีละตัว แก้หลายจุดพร้อมกัน",
      "Cmd+Shift+L เลือกคำเดียวกันทั้งหมดในไฟล์",
      "ใช้ .vscode/settings.json ตั้งค่าเฉพาะโปรเจกต์",
      "ติดตั้ง Vim extension ถ้าอยากได้ speed ของ Vim ใน VS Code",
    ],
    alternatives: ["Cursor", "WebStorm", "Sublime Text", "Neovim", "Zed"],
  },
  {
    name: "Cursor",
    slug: "cursor",
    tagline: "AI-first Code Editor สำหรับยุคใหม่",
    description: "Cursor คือ VS Code ที่ถูก fork มาและใส่ AI เข้าไปอย่างลึก — chat กับ codebase, แก้โค้ดด้วย AI, autocomplete แบบอัจฉริยะ เปลี่ยนวิธีเขียนโค้ดไปเลย",
    icon: "🖱️",
    category: "editor",
    pricing: "freemium",
    platforms: ["Windows", "macOS", "Linux"],
    url: "https://cursor.com",
    whyUse: [
      "AI ที่เข้าใจ codebase ทั้งโปรเจกต์ ไม่ใช่แค่ไฟล์เดียว",
      "Tab autocomplete ที่ฉลาดกว่า Copilot มาก",
      "Chat กับโค้ดได้ — ถาม อธิบาย แก้บัก refactor",
      "ใช้ extension ของ VS Code ได้ทั้งหมด",
      "Agent mode ทำงานหลาย step อัตโนมัติ",
    ],
    keyFeatures: [
      "Cmd+K — แก้โค้ด inline ด้วย AI",
      "Cmd+L — Chat กับ AI พร้อม context ของ codebase",
      "Tab Autocomplete — เดา next edit ได้แม่นมาก",
      "Agent Mode — ให้ AI สร้างไฟล์ แก้โค้ด รัน command หลาย step",
      "@ Mentions — อ้างอิงไฟล์ ฟังก์ชัน docs ใน chat",
      "รองรับ VS Code Extensions ทั้งหมด",
    ],
    quickStart: [
      "ดาวน์โหลดจาก cursor.com",
      "Import settings จาก VS Code ได้ตอน setup",
      "เปิดโปรเจกต์แล้วลอง Cmd+L เพื่อ chat กับ AI",
      "ลอง Cmd+K เพื่อแก้โค้ดด้วยภาษาธรรมชาติ",
      "เรียนรู้ @ mentions เพื่อให้ AI เข้าใจ context ดีขึ้น",
    ],
    proTips: [
      "ใช้ .cursorrules เพื่อกำหนดแนวทางให้ AI ตาม coding style ของทีม",
      "อ้างอิง @docs เพื่อให้ AI อ่าน documentation ที่เกี่ยวข้อง",
      "ใช้ Agent mode สำหรับงานที่ต้องแก้หลายไฟล์พร้อมกัน",
      "ตั้งค่า model ที่ต้องการใช้ — Claude, GPT-4o, หรืออื่นๆ",
    ],
    alternatives: ["VS Code + Copilot", "Windsurf", "Zed", "JetBrains AI"],
  },
  {
    name: "WebStorm",
    slug: "webstorm",
    tagline: "IDE เต็มรูปแบบสำหรับ JavaScript/TypeScript",
    description: "WebStorm จาก JetBrains เป็น IDE ที่ออกแบบมาสำหรับ web dev โดยเฉพาะ — refactoring ดีมาก debugger ทรงพลัง เข้าใจ framework เช่น React, Next.js, Vue ลึกซึ้ง",
    icon: "🌊",
    category: "editor",
    pricing: "freemium",
    platforms: ["Windows", "macOS", "Linux"],
    url: "https://www.jetbrains.com/webstorm",
    whyUse: [
      "Refactoring ดีที่สุดใน class — rename, extract, move ได้ทั้ง project",
      "Debugger ที่ทรงพลังกว่า VS Code สำหรับ Node.js",
      "เข้าใจ framework ลึก เช่น component props, route structure",
      "ไม่ต้องติดตั้ง extension เยอะ ทุกอย่างมาครบ",
    ],
    keyFeatures: [
      "Smart Code Completion — autocomplete ที่เข้าใจ context",
      "Refactoring — rename, extract method, move file ได้ทั้ง project",
      "Built-in Debugger — step through, breakpoints, watch variables",
      "Framework Support — React, Vue, Angular, Next.js, Svelte",
      "Built-in HTTP Client — ทดสอบ API ได้ใน IDE",
      "Database Tools — connect และ query database ได้เลย",
    ],
    quickStart: [
      "ดาวน์โหลดจาก jetbrains.com/webstorm",
      "เปิดโปรเจกต์: File → Open",
      "ตั้งค่า Node.js interpreter: Preferences → Languages → Node.js",
      "เรียนรู้ Shortcut: Shift+Shift (Search Everywhere)",
      "ลอง Refactoring: คลิกขวา → Refactor → Rename",
    ],
    proTips: [
      "ใช้ Shift+Shift เพื่อค้นหาทุกอย่าง — ไฟล์ ฟังก์ชัน settings",
      "ตั้ง Run Configuration สำหรับ dev server, test, build",
      "ใช้ Local History เมื่อต้องการย้อนกลับโดยไม่ใช้ Git",
      "เปิด AI Assistant ช่วยเขียนโค้ดได้ (ต้อง subscription เพิ่ม)",
    ],
    alternatives: ["VS Code", "Cursor", "Sublime Text"],
  },

  // ─── TERMINAL & SHELL ───
  {
    name: "iTerm2 / Windows Terminal",
    slug: "iterm2",
    tagline: "Terminal ที่ดีกว่า default ของ OS",
    description: "iTerm2 (macOS) และ Windows Terminal (Windows) เป็น terminal emulator ที่ดีกว่าตัว default มาก — split panes, tabs, search, themes, profiles ทำให้ทำงานบน command line สะดวกขึ้นเยอะ",
    icon: "🖥️",
    category: "terminal",
    pricing: "free",
    platforms: ["macOS (iTerm2)", "Windows (Windows Terminal)"],
    url: "https://iterm2.com",
    whyUse: [
      "Split panes ดูหลาย terminal พร้อมกัน",
      "Tabs จัดการหลาย session ได้ง่าย",
      "Search ค้นหา output ที่ผ่านมาได้",
      "Profiles ตั้งค่าแยกตามโปรเจกต์ — สี, font, directory เริ่มต้น",
      "Hotkey window เปิด terminal ได้ทันทีจากทุกแอป",
    ],
    keyFeatures: [
      "Split Panes — แบ่งหน้าจอดู terminal หลายตัวพร้อมกัน",
      "Autocomplete — แนะนำคำสั่งจาก history",
      "Search — ค้นหาข้อความใน terminal output",
      "Profiles — ตั้งค่า theme, font, working directory แยกตามงาน",
      "Shell Integration — แสดง timestamp, command status",
      "Hotkey Window — กด shortcut เดียวเปิด terminal ทันที",
    ],
    quickStart: [
      "macOS: brew install --cask iterm2",
      "Windows: ติดตั้ง Windows Terminal จาก Microsoft Store",
      "ติดตั้ง Oh My Zsh: sh -c \"$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\"",
      "เลือก theme ที่ชอบ: Powerlevel10k, Starship, หรือ Pure",
      "ตั้งค่า font เป็น Nerd Font เพื่อให้ icon แสดงถูกต้อง",
    ],
    proTips: [
      "ใช้ Cmd+D split แนวตั้ง, Cmd+Shift+D split แนวนอน",
      "ตั้ง Hotkey Window ไว้ที่ ` หรือ F12 เปิดได้ทุกเวลา",
      "ใช้ tmux สำหรับ session management บน remote server",
      "ลอง fish shell ถ้าอยากได้ autocomplete ที่ฉลาดมากขึ้น",
    ],
    alternatives: ["Warp", "Alacritty", "Hyper", "Kitty"],
  },
  {
    name: "Oh My Zsh",
    slug: "oh-my-zsh",
    tagline: "ทำให้ terminal สวย ฉลาด ใช้ง่ายขึ้นเยอะ",
    description: "Oh My Zsh คือ framework สำหรับจัดการ Zsh config — มี theme สวยๆ plugin ช่วยทำงาน alias ย่อคำสั่ง ทำให้ terminal จากน่าเบื่อกลายเป็นสนุกและ productive",
    icon: "🐚",
    category: "terminal",
    pricing: "open-source",
    platforms: ["macOS", "Linux", "WSL"],
    url: "https://ohmyz.sh",
    whyUse: [
      "Theme สวยๆ แสดง git branch, status, เวลา ได้ใน prompt",
      "Plugin ช่วยทำงาน — git, docker, npm, kubectl, auto-suggestions",
      "Alias ย่อคำสั่งยาวๆ เช่น gst = git status",
      "Tab completion ที่ดีกว่า bash มาก",
    ],
    keyFeatures: [
      "300+ themes เลือกได้ตาม style",
      "300+ plugins สำหรับทุก tool",
      "Git plugin — gst, gco, gp, gl ย่อคำสั่ง git",
      "zsh-autosuggestions — แนะนำคำสั่งจาก history แบบ real-time",
      "zsh-syntax-highlighting — สีคำสั่งให้รู้ถูก/ผิดก่อนกด Enter",
      "Auto-update ทุก 2 สัปดาห์",
    ],
    quickStart: [
      "ติดตั้ง: sh -c \"$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\"",
      "เปลี่ยน theme ใน ~/.zshrc: ZSH_THEME=\"robbyrussell\"",
      "เพิ่ม plugins: plugins=(git docker npm zsh-autosuggestions)",
      "source ~/.zshrc เพื่อให้มีผลทันที",
      "ลอง Powerlevel10k theme สำหรับ prompt ที่สวยที่สุด",
    ],
    proTips: [
      "ติดตั้ง zsh-autosuggestions + zsh-syntax-highlighting ก่อนเลย",
      "ใช้ alias สร้างคำสั่งย่อของตัวเอง: alias dc='docker compose'",
      "ลอง Powerlevel10k theme พร้อม wizard ตั้งค่าสวยมาก",
      "ใช้ .zshrc.local สำหรับ config เฉพาะเครื่อง ไม่ commit ขึ้น Git",
    ],
    alternatives: ["Starship", "Fish Shell", "Prezto"],
  },

  // ─── GIT & VERSION CONTROL ───
  {
    name: "Git",
    slug: "git",
    tagline: "Version control ที่ dev ทุกคนต้องรู้",
    description: "Git คือระบบ version control ที่ใช้กันทั่วโลก — ติดตามการเปลี่ยนแปลงของโค้ด ทำงานร่วมกันเป็นทีม ย้อนกลับได้ แตก branch ได้ เป็น skill ที่ต้องรู้ก่อนอื่นใด",
    icon: "🔀",
    category: "git",
    pricing: "open-source",
    platforms: ["Windows", "macOS", "Linux"],
    url: "https://git-scm.com",
    whyUse: [
      "ติดตามทุกการเปลี่ยนแปลง ย้อนกลับได้ตลอดเวลา",
      "ทำงานเป็นทีมโดยไม่ทับโค้ดกัน ด้วย branching",
      "ใช้เป็นพื้นฐานของ GitHub, GitLab, Bitbucket",
      "มาตรฐานอุตสาหกรรม — บริษัทไหนก็ใช้ Git",
    ],
    keyFeatures: [
      "Branching — แยก branch ทำฟีเจอร์ แก้บัก แล้ว merge กลับ",
      "History — ดูว่าใครแก้อะไร เมื่อไหร่ ทำไม",
      "Staging Area — เลือกเฉพาะไฟล์ที่จะ commit ได้",
      "Stash — เก็บงานชั่วคราว ไปทำอย่างอื่น แล้วกลับมาทำต่อ",
      "Revert/Reset — ย้อนกลับถ้าทำพลาด",
      "Tags — ติด tag เวอร์ชัน v1.0, v2.0",
    ],
    quickStart: [
      "ติดตั้ง: brew install git (macOS) หรือ apt install git (Linux)",
      "ตั้งชื่อ: git config --global user.name \"ชื่อ\"",
      "ตั้ง email: git config --global user.email \"email@example.com\"",
      "เริ่มใช้: git init → git add . → git commit -m \"first commit\"",
      "เชื่อม GitHub: git remote add origin <url> → git push -u origin main",
    ],
    proTips: [
      "ใช้ Conventional Commits: feat:, fix:, docs:, refactor:",
      "ตั้ง alias: git config --global alias.co checkout",
      "ใช้ .gitignore ไม่ commit node_modules, .env, build",
      "เรียนรู้ git rebase -i สำหรับ squash commits ก่อน merge",
    ],
    alternatives: ["Mercurial", "SVN (Subversion)"],
  },
  {
    name: "GitHub",
    slug: "github",
    tagline: "แพลตฟอร์มหลักสำหรับ host code และทำงานร่วมกัน",
    description: "GitHub คือที่เก็บโค้ดออนไลน์ที่ใหญ่ที่สุดในโลก — Pull Request, Issues, Actions, Pages ครบวงจร เป็นทั้งที่เก็บโค้ด CI/CD portfolio และชุมชน open-source",
    icon: "🐙",
    category: "git",
    pricing: "freemium",
    platforms: ["Web", "Desktop App", "CLI (gh)"],
    url: "https://github.com",
    whyUse: [
      "เก็บโค้ดออนไลน์ backup อัตโนมัติ เข้าถึงจากทุกที่",
      "Pull Request + Code Review ทำงานเป็นทีมอย่างมีระบบ",
      "GitHub Actions ทำ CI/CD ฟรี ทดสอบ + deploy อัตโนมัติ",
      "GitHub Pages host เว็บ static ฟรี",
      "Profile = portfolio — แสดง contributions, projects ของเรา",
    ],
    keyFeatures: [
      "Repositories — เก็บ code, wiki, issues ของแต่ละ project",
      "Pull Requests — ขอ merge code + code review",
      "Issues — ติดตาม bug, feature request, tasks",
      "Actions — CI/CD pipeline อัตโนมัติ",
      "Pages — host เว็บ static ฟรี",
      "Copilot — AI ช่วยเขียนโค้ด",
      "Codespaces — dev environment บน cloud",
    ],
    quickStart: [
      "สมัครที่ github.com",
      "สร้าง repository ใหม่: New → ตั้งชื่อ → Create",
      "ติดตั้ง GitHub CLI: brew install gh",
      "Login: gh auth login",
      "Clone: gh repo clone username/repo",
    ],
    proTips: [
      "ใช้ gh CLI ทำทุกอย่างจาก terminal — pr create, issue list",
      "ตั้ง Branch Protection Rule ป้องกัน push ตรงเข้า main",
      "ใช้ GitHub Actions ทำ CI ฟรี — test ทุก PR อัตโนมัติ",
      "สร้าง profile README ที่ username/username repo",
    ],
    alternatives: ["GitLab", "Bitbucket", "Gitea"],
  },

  // ─── API & HTTP TESTING ───
  {
    name: "Postman",
    slug: "postman",
    tagline: "ทดสอบ API แบบง่ายๆ ด้วย GUI",
    description: "Postman คือเครื่องมือยอดนิยมสำหรับทดสอบ API — สร้าง request ดูผลลัพธ์ จัดกลุ่ม collection เขียน test อัตโนมัติ แชร์กับทีม เป็นเครื่องมือคู่ใจ backend developer",
    icon: "📮",
    category: "api",
    pricing: "freemium",
    platforms: ["Windows", "macOS", "Linux", "Web"],
    url: "https://www.postman.com",
    whyUse: [
      "ทดสอบ API ได้ง่ายผ่าน GUI ไม่ต้องเขียน code",
      "จัดกลุ่ม request เป็น Collection ใช้ซ้ำได้",
      "Environment variables แยก dev/staging/production",
      "เขียน test + assertion ตรวจสอบ response อัตโนมัติ",
      "สร้าง API documentation อัตโนมัติ",
    ],
    keyFeatures: [
      "Request Builder — สร้าง GET, POST, PUT, DELETE ง่ายๆ",
      "Collections — จัดกลุ่ม request ตาม feature/module",
      "Environment — สลับ URL ระหว่าง dev, staging, prod",
      "Tests & Scripts — เขียน test ตรวจ status code, body",
      "Mock Server — จำลอง API ก่อน backend เสร็จ",
      "Team Workspace — แชร์ collection กับทีม",
    ],
    quickStart: [
      "ดาวน์โหลดจาก postman.com หรือใช้ web version",
      "สร้าง request: New → HTTP Request → ใส่ URL → Send",
      "สร้าง Collection: New → Collection → เพิ่ม request เข้าไป",
      "ตั้ง Environment: เพิ่ม variable เช่น {{base_url}}",
      "เขียน Test: tab Tests → pm.test('status 200', ...)",
    ],
    proTips: [
      "ใช้ {{variable}} แทน hardcode URL/token",
      "ตั้ง Pre-request Script ดึง token อัตโนมัติก่อนทุก request",
      "Export collection เป็น JSON เก็บไว้ใน Git",
      "ใช้ Newman (CLI) รัน collection ใน CI/CD pipeline",
    ],
    alternatives: ["Bruno", "Insomnia", "Thunder Client (VS Code)", "HTTPie", "curl"],
  },
  {
    name: "Bruno",
    slug: "bruno",
    tagline: "API Client แบบ open-source เก็บใน Git ได้",
    description: "Bruno เป็น API client ทางเลือกใหม่ที่ open-source และเก็บ request เป็นไฟล์ในโปรเจกต์ — ไม่ต้อง sync กับ cloud, version control ด้วย Git ได้เลย, ทีมใช้ร่วมกันง่าย",
    icon: "🐶",
    category: "api",
    pricing: "open-source",
    platforms: ["Windows", "macOS", "Linux"],
    url: "https://www.usebruno.com",
    whyUse: [
      "Open-source และ offline — ไม่ต้องส่งข้อมูลไป cloud",
      "เก็บ request เป็นไฟล์ .bru ใน Git ร่วมกับโค้ด",
      "ฟรี 100% ไม่มี subscription หรือ feature ล็อก",
      "UI สะอาด ใช้ง่าย เร็ว",
    ],
    keyFeatures: [
      "Git-friendly — request เป็นไฟล์ text commit ได้",
      "Collections — จัดกลุ่มตาม folder structure",
      "Environment Variables — แยก dev/prod config",
      "Scripting — Pre-request + Post-response scripts",
      "No cloud — data อยู่ในเครื่อง 100%",
    ],
    quickStart: [
      "ดาวน์โหลดจาก usebruno.com",
      "Create Collection → เลือก folder ในโปรเจกต์",
      "New Request → ตั้งชื่อ, เลือก method, ใส่ URL",
      "Send แล้วดูผลลัพธ์",
      "git add . เพื่อ commit request ร่วมกับโค้ด",
    ],
    proTips: [
      "เก็บ collection ไว้ใน folder api/ ของโปรเจกต์",
      "ใช้ .env file ร่วมกับ Bruno environments",
      "Import collection จาก Postman ได้โดยตรง",
    ],
    alternatives: ["Postman", "Insomnia", "Thunder Client"],
  },

  // ─── DATABASE TOOLS ───
  {
    name: "DBeaver",
    slug: "dbeaver",
    tagline: "Database GUI ที่รองรับ DB ทุกตัว",
    description: "DBeaver เป็น database management tool ที่รองรับ PostgreSQL, MySQL, MongoDB, SQLite และอีกมากมาย — เขียน query, ดู data, export/import, ER diagram ได้ครบ",
    icon: "🦫",
    category: "database",
    pricing: "freemium",
    platforms: ["Windows", "macOS", "Linux"],
    url: "https://dbeaver.io",
    whyUse: [
      "รองรับ database มากกว่า 80 ตัว ในแอปเดียว",
      "SQL editor ที่มี autocomplete, syntax highlighting",
      "ดู data แบบ spreadsheet แก้ไขได้เลย",
      "ER Diagram แสดงความสัมพันธ์ระหว่างตาราง",
      "Community Edition ฟรี 100%",
    ],
    keyFeatures: [
      "SQL Editor — เขียน query พร้อม autocomplete",
      "Data Viewer — ดู/แก้/กรอง data แบบ spreadsheet",
      "ER Diagram — visualize ความสัมพันธ์",
      "Import/Export — CSV, JSON, SQL dump",
      "SSH Tunnel — เชื่อม database ผ่าน SSH",
      "Compare — เปรียบเทียบ schema ระหว่าง 2 database",
    ],
    quickStart: [
      "ดาวน์โหลด Community Edition จาก dbeaver.io",
      "New Connection → เลือก database type",
      "ใส่ host, port, username, password",
      "Test Connection → Finish",
      "เปิด SQL Editor → เขียน query → Execute (Ctrl+Enter)",
    ],
    proTips: [
      "ใช้ Ctrl+Enter รัน query ที่เลือก (ไม่ต้องรันทั้งหมด)",
      "ตั้ง Connection Pool ถ้าเชื่อมหลาย database",
      "Export ผลลัพธ์เป็น CSV/JSON สำหรับ analysis",
      "ใช้ SSH Tunnel เมื่อเชื่อม database บน cloud",
    ],
    alternatives: ["TablePlus", "DataGrip", "pgAdmin", "MySQL Workbench"],
  },
  {
    name: "Prisma Studio",
    slug: "prisma-studio",
    tagline: "GUI สำหรับ Prisma ORM ดู/แก้ data ง่ายๆ",
    description: "Prisma Studio เป็น GUI ที่มากับ Prisma ORM — เปิด browser ดู data ในตาราง แก้ไข เพิ่ม ลบ ได้เลย เหมาะสำหรับ development ไม่ต้องเขียน SQL",
    icon: "💎",
    category: "database",
    pricing: "open-source",
    platforms: ["Web (localhost)"],
    url: "https://www.prisma.io/studio",
    whyUse: [
      "ดูและแก้ data ในแต่ละ model ผ่าน browser",
      "ไม่ต้องเขียน SQL เลย",
      "มากับ Prisma ฟรี ไม่ต้องติดตั้งเพิ่ม",
      "เข้าใจ relations อัตโนมัติจาก Prisma schema",
    ],
    keyFeatures: [
      "Table View — ดู data ทุก model แบบ spreadsheet",
      "CRUD — เพิ่ม แก้ ลบ record ได้ทันที",
      "Relations — navigate ไปยัง related records",
      "Filter & Sort — กรองและเรียงข้อมูล",
    ],
    quickStart: [
      "ต้องมี Prisma setup ในโปรเจกต์แล้ว",
      "รัน: npx prisma studio",
      "เปิด browser ที่ http://localhost:5555",
      "เลือก model ที่ต้องการดู/แก้ data",
    ],
    proTips: [
      "ใช้ตอน development เพื่อ debug data ได้เร็ว",
      "อย่าใช้กับ production database ตรงๆ",
      "ใช้ร่วมกับ prisma db seed เพื่อใส่ test data",
    ],
    alternatives: ["DBeaver", "TablePlus", "Drizzle Studio"],
  },

  // ─── CONTAINER & DEVOPS ───
  {
    name: "Docker Desktop",
    slug: "docker-desktop",
    tagline: "รัน container บนเครื่องตัวเองง่ายๆ",
    description: "Docker Desktop ทำให้ใช้ Docker บนเครื่อง dev ง่ายขึ้น — มี GUI จัดการ containers, images, volumes พร้อม Kubernetes ในตัว ไม่ต้อง setup เอง",
    icon: "🐳",
    category: "container",
    pricing: "freemium",
    platforms: ["Windows", "macOS", "Linux"],
    url: "https://www.docker.com/products/docker-desktop",
    whyUse: [
      "รัน database, cache, service บนเครื่องโดยไม่ต้องติดตั้งจริง",
      "Dockerfile + Docker Compose จำลองสภาพแวดล้อมเหมือน production",
      "ทีมใช้ config เดียวกัน ไม่มีปัญหา \"เครื่องผมรันได้\"",
      "GUI ดูสถานะ containers, logs, resource usage",
    ],
    keyFeatures: [
      "Container Management — start/stop/restart ผ่าน GUI",
      "Docker Compose — รัน multi-container app ด้วยคำสั่งเดียว",
      "Volume Management — จัดการ persistent data",
      "Image Browser — ค้นหา image จาก Docker Hub",
      "Kubernetes — เปิด K8s cluster บนเครื่อง dev",
      "Extensions — เพิ่ม tool อื่นๆ เช่น log viewer, vulnerability scan",
    ],
    quickStart: [
      "ดาวน์โหลดจาก docker.com/products/docker-desktop",
      "ติดตั้งแล้วเปิดแอป Docker Desktop",
      "ลอง: docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=pass postgres",
      "ดู container ที่รัน: docker ps",
      "หยุด: docker stop <container_id>",
    ],
    proTips: [
      "ใช้ docker-compose.yml สำหรับ dev environment — DB + Redis + App",
      "ตั้ง resource limits (CPU, RAM) ใน Settings เพื่อไม่ให้เครื่องช้า",
      "ใช้ .dockerignore ไม่ copy node_modules เข้า image",
      "ใช้ multi-stage builds สำหรับ production image ให้เล็กลง",
    ],
    alternatives: ["Podman", "Rancher Desktop", "OrbStack (macOS)"],
  },

  // ─── DESIGN & UI ───
  {
    name: "Figma",
    slug: "figma",
    tagline: "ออกแบบ UI และ prototype ร่วมกันแบบ real-time",
    description: "Figma เป็นเครื่องมือออกแบบ UI/UX อันดับ 1 — ทำงานบน browser ได้เลย designer กับ developer ดู/ส่งมอบงานกันง่าย inspect CSS/code ได้ มี dev mode สำหรับ developer",
    icon: "🎨",
    category: "design",
    pricing: "freemium",
    platforms: ["Web", "Windows", "macOS"],
    url: "https://www.figma.com",
    whyUse: [
      "ดู design ที่ designer ส่งมาได้ทันที ไม่ต้องติดตั้งอะไร",
      "Inspect mode — ดูสี, font, spacing, CSS ของ element ได้",
      "Dev Mode — export code, assets, token ได้เลย",
      "Collaboration — comment, แก้ไข, ดูพร้อมกันแบบ real-time",
      "เข้าใจ design system = คุยกับ designer รู้เรื่อง",
    ],
    keyFeatures: [
      "Design — สร้าง UI components, layouts, screens",
      "Prototype — สร้าง interactive prototype คลิกได้จริง",
      "Dev Mode — inspect ขนาด สี spacing และ export code",
      "Components — reusable UI elements เหมือน React components",
      "Auto Layout — responsive layout คล้าย Flexbox",
      "Plugins — เพิ่ม icons, illustrations, lorem ipsum",
    ],
    quickStart: [
      "สมัครที่ figma.com (ฟรี สำหรับ 3 projects)",
      "เปิด design ที่ designer แชร์มา",
      "คลิก element → ดู Properties ทางขวา (สี, ขนาด, spacing)",
      "เปิด Dev Mode (Shift+D) เพื่อดู code snippet",
      "Export assets: คลิกขวา → Export → PNG/SVG",
    ],
    proTips: [
      "ใช้ Dev Mode ดู CSS/Tailwind code ของแต่ละ element",
      "ดู spacing ด้วย Alt+hover ระหว่าง elements",
      "ใช้ Figma tokens ร่วมกับ design system ของทีม",
      "ลอง Figma to Code plugin สำหรับ export React code",
    ],
    alternatives: ["Sketch", "Adobe XD", "Penpot (open-source)"],
  },

  // ─── COLLABORATION & PM ───
  {
    name: "Jira",
    slug: "jira",
    tagline: "Project management สำหรับทีม Agile/Scrum",
    description: "Jira จาก Atlassian เป็นเครื่องมือจัดการโปรเจกต์ที่นิยมที่สุดในวงการ software — Sprint board, Backlog, Ticket tracking, Workflow ครบวงจร ทั้ง Scrum และ Kanban",
    icon: "📋",
    category: "collab",
    pricing: "freemium",
    platforms: ["Web", "iOS", "Android"],
    url: "https://www.atlassian.com/software/jira",
    whyUse: [
      "จัดการ Sprint, Backlog, Sprint Review ได้ครบวงจร",
      "Ticket tracking — ติดตามงานตั้งแต่ To Do ถึง Done",
      "Custom Workflow — กำหนดขั้นตอนงานตามที่ทีมต้องการ",
      "Integration — เชื่อมกับ GitHub, Slack, Confluence",
      "มาตรฐานอุตสาหกรรม — บริษัทส่วนใหญ่ใช้ Jira",
    ],
    keyFeatures: [
      "Scrum Board — Sprint planning, Daily standup",
      "Kanban Board — To Do → In Progress → Done",
      "Backlog — จัดลำดับ priority, estimate story points",
      "Epics & Stories — แบ่งงานเป็น hierarchy",
      "Reports — Burndown chart, Velocity, Sprint report",
      "Automation — ย้าย status อัตโนมัติเมื่อ PR merged",
    ],
    quickStart: [
      "สมัครที่ atlassian.com (ฟรี ≤10 คน)",
      "สร้าง Project: เลือก Scrum หรือ Kanban",
      "สร้าง Story: Backlog → Create Issue → กรอกรายละเอียด",
      "เริ่ม Sprint: เลือก stories เข้า Sprint → Start Sprint",
      "ย้าย ticket ตาม progress: To Do → In Progress → Done",
    ],
    proTips: [
      "เชื่อม GitHub ให้ PR link กับ Jira ticket อัตโนมัติ (PROJ-123 ใน branch name)",
      "ใช้ JQL (Jira Query Language) ค้นหา ticket ซับซ้อน",
      "ตั้ง Automation: เมื่อ PR merged → ย้าย ticket เป็น Done",
      "ใช้ Sprint Retrospective board ใน Jira",
    ],
    alternatives: ["Linear", "Asana", "Trello", "Notion", "ClickUp"],
  },
  {
    name: "Slack",
    slug: "slack",
    tagline: "แชทสำหรับทีม dev มี bot และ integration เยอะ",
    description: "Slack เป็นแอปสื่อสารหลักของทีม dev — แยกเป็น channels ตามเรื่อง, thread ไม่รบกวนคนอื่น, bot แจ้งเตือน CI/CD, deploy, error ได้อัตโนมัติ",
    icon: "💬",
    category: "collab",
    pricing: "freemium",
    platforms: ["Web", "Windows", "macOS", "Linux", "iOS", "Android"],
    url: "https://slack.com",
    whyUse: [
      "แยก channel ตาม team/project/topic ไม่ปนกัน",
      "Thread — ตอบแบบไม่รบกวน channel หลัก",
      "Integration — GitHub, Jira, CI/CD แจ้งเตือนอัตโนมัติ",
      "Huddle — voice call เร็วๆ ไม่ต้องนัด meeting",
      "Search — ค้นหาข้อความ ไฟล์ ย้อนหลังได้",
    ],
    keyFeatures: [
      "Channels — #frontend, #backend, #devops, #random",
      "Threads — สนทนาแยกเรื่อง ไม่ spam channel",
      "Bots — GitHub bot, CI bot, deploy bot",
      "Huddles — voice/video call แบบ drop-in",
      "Workflow Builder — สร้าง automation ง่ายๆ",
      "Code Snippets — แชร์โค้ดพร้อม syntax highlighting",
    ],
    quickStart: [
      "สมัครที่ slack.com หรือรับ invite จากทีม",
      "เข้า channels ที่เกี่ยวข้อง",
      "ใช้ thread ตอบแทนส่ง message ใน channel",
      "ตั้ง notification schedule — เลือกเวลาที่แจ้งเตือน",
      "ติดตั้ง GitHub + Jira integration",
    ],
    proTips: [
      "ใช้ /remind เตือนตัวเอง: /remind me to review PR in 2 hours",
      "ตั้ง Do Not Disturb ตอนต้อง focus",
      "ใช้ Cmd+K ค้นหา channel, คน, ข้อความ เร็วมาก",
      "สร้าง channel #til (Today I Learned) แชร์ความรู้กัน",
    ],
    alternatives: ["Discord", "Microsoft Teams", "Google Chat"],
  },
  {
    name: "Notion",
    slug: "notion",
    tagline: "All-in-one workspace สำหรับ docs, wiki, tasks",
    description: "Notion รวม notes, docs, wiki, database, task board ไว้ในที่เดียว — ใช้เก็บ knowledge, เขียน spec, ติดตามงาน, onboarding docs ยืดหยุ่นมากจัด layout ได้ตามใจ",
    icon: "📓",
    category: "collab",
    pricing: "freemium",
    platforms: ["Web", "Windows", "macOS", "iOS", "Android"],
    url: "https://www.notion.so",
    whyUse: [
      "เก็บ knowledge ของทีมไว้ที่เดียว — wiki, runbook, ADR",
      "เขียน technical spec, RFC, design document",
      "Database views — ดูข้อมูลเป็น table, kanban, calendar, gallery",
      "Template — ใช้ template สำเร็จรูปหรือสร้างเอง",
    ],
    keyFeatures: [
      "Pages — nested pages เหมือน wiki",
      "Database — table, kanban, calendar, gallery views",
      "Templates — meeting notes, sprint retro, project tracker",
      "AI — สรุป, เขียน, แปล ด้วย Notion AI",
      "Embed — ฝัง Figma, GitHub, Google Docs ได้",
      "API — เชื่อมกับ tool อื่นผ่าน API",
    ],
    quickStart: [
      "สมัครที่ notion.so (ฟรี สำหรับ personal)",
      "สร้าง Workspace สำหรับทีม",
      "สร้าง page แรก: Engineering Wiki",
      "เพิ่ม sub-pages: Onboarding, Architecture, Runbooks",
      "ลองสร้าง database: Task tracker แบบ Kanban",
    ],
    proTips: [
      "ใช้ / command พิมพ์ / แล้วเลือก block type ได้เลย",
      "สร้าง ADR template: Context → Decision → Consequences",
      "ใช้ Notion API + GitHub Actions อัปเดต docs อัตโนมัติ",
      "Toggle list ซ่อนรายละเอียดที่ไม่จำเป็น",
    ],
    alternatives: ["Confluence", "Coda", "Obsidian", "Outline"],
  },

  // ─── BROWSER & DEV TOOLS ───
  {
    name: "Chrome DevTools",
    slug: "chrome-devtools",
    tagline: "Debug เว็บในเบราว์เซอร์ ดู HTML/CSS/JS/Network",
    description: "Chrome DevTools คือเครื่องมือ built-in ของ Chrome สำหรับ debug เว็บ — inspect element, ดู network requests, debug JavaScript, วิเคราะห์ performance, ทดสอบ responsive ครบหมด",
    icon: "🔧",
    category: "browser",
    pricing: "free",
    platforms: ["Chrome", "Edge (เหมือนกัน)", "Brave"],
    url: "https://developer.chrome.com/docs/devtools",
    whyUse: [
      "Inspect element — ดูและแก้ HTML/CSS แบบ real-time",
      "Console — รัน JavaScript, ดู errors, log ค่าตัวแปร",
      "Network — ดูทุก request/response, ตรวจ API calls",
      "Performance — วิเคราะห์ว่าเว็บช้าตรงไหน",
      "ฟรี มากับ Chrome ไม่ต้องติดตั้งอะไรเพิ่ม",
    ],
    keyFeatures: [
      "Elements — inspect/แก้ HTML + CSS real-time",
      "Console — log, error, รัน JS ได้ทันที",
      "Network — ดู HTTP requests, status, timing, payload",
      "Sources — debug JS ด้วย breakpoints",
      "Application — ดู localStorage, cookies, service workers",
      "Lighthouse — audit performance, accessibility, SEO",
      "Responsive Mode — ทดสอบ mobile view",
    ],
    quickStart: [
      "เปิด Chrome → กด F12 หรือ Cmd+Option+I",
      "Elements tab: คลิกขวาที่ element → Inspect",
      "Console tab: พิมพ์ console.log('test') แล้ว Enter",
      "Network tab: refresh หน้าแล้วดู requests ทั้งหมด",
      "Responsive: คลิก icon มือถือ (Cmd+Shift+M)",
    ],
    proTips: [
      "คลิกขวา element → Break on → subtree modifications ติดตาม DOM changes",
      "Network tab: คลิกขวา → Copy as fetch / Copy as cURL",
      "ใช้ $0 ใน Console อ้างอิง element ที่เลือกอยู่",
      "Performance tab: Record แล้ว interact กับเว็บ ดู flame chart",
    ],
    alternatives: ["Firefox DevTools", "Safari Web Inspector"],
  },
  {
    name: "React DevTools",
    slug: "react-devtools",
    tagline: "Debug React components, state, props ได้ลึก",
    description: "React DevTools เป็น browser extension ที่ให้ดู component tree, props, state, hooks ของ React app — debug ง่ายมาก ดูว่า component ไหน re-render ทำไม",
    icon: "⚛️",
    category: "browser",
    pricing: "free",
    platforms: ["Chrome Extension", "Firefox Extension", "Edge Extension"],
    url: "https://react.dev/learn/react-developer-tools",
    whyUse: [
      "ดู component tree — เข้าใจโครงสร้าง React app",
      "ดู/แก้ props, state, hooks ของทุก component",
      "Profiler — หา component ที่ render ช้าหรือ render บ่อยเกิน",
      "ฟรี เป็น extension ติดตั้งง่าย",
    ],
    keyFeatures: [
      "Components tab — ดู component tree + props/state/hooks",
      "Profiler — record renders, ดู flame chart",
      "Highlight Updates — เห็นว่า component ไหน re-render",
      "Search — ค้นหา component ด้วยชื่อ",
      "Edit State/Props — แก้ค่าแบบ live ใน DevTools",
    ],
    quickStart: [
      "ติดตั้ง extension จาก Chrome Web Store",
      "เปิดเว็บ React → F12 → จะเห็น tab Components กับ Profiler",
      "คลิก component ใน tree → ดู props, state ทางขวา",
      "Profiler → Start Recording → interact → Stop → ดูผลลัพธ์",
    ],
    proTips: [
      "เปิด \"Highlight updates when components render\" ดู re-render แบบ visual",
      "ใช้ Profiler หา unnecessary re-renders แล้วแก้ด้วย React.memo / useMemo",
      "คลิก component แล้วพิมพ์ $r ใน console เพื่อเข้าถึง component instance",
    ],
    alternatives: ["Vue DevTools", "Svelte DevTools", "Angular DevTools"],
  },

  // ─── AI-POWERED TOOLS ───
  {
    name: "GitHub Copilot",
    slug: "github-copilot",
    tagline: "AI ช่วยเขียนโค้ดแบบ real-time",
    description: "GitHub Copilot คือ AI pair programmer ที่ suggest โค้ดขณะพิมพ์ — เข้าใจ context จาก comment และโค้ดรอบข้าง autocomplete ทั้งบรรทัดหรือทั้ง function",
    icon: "🤖",
    category: "ai",
    pricing: "paid",
    platforms: ["VS Code", "JetBrains", "Neovim", "Visual Studio"],
    url: "https://github.com/features/copilot",
    whyUse: [
      "เขียนโค้ดเร็วขึ้น 30-50% ด้วย AI autocomplete",
      "เขียน comment อธิบาย → Copilot สร้างโค้ดให้",
      "สร้าง test, boilerplate, utility functions อัตโนมัติ",
      "เข้าใจ pattern จากโค้ดรอบข้าง suggest ได้ตรงจุด",
    ],
    keyFeatures: [
      "Inline Suggestions — suggest โค้ดขณะพิมพ์",
      "Copilot Chat — ถาม/อธิบาย/debug ในตัว editor",
      "Multi-line Completion — สร้างทั้งฟังก์ชันได้",
      "Test Generation — สร้าง unit test จากโค้ด",
      "Explain Code — อธิบายโค้ดที่ไม่เข้าใจ",
      "Fix Errors — แนะนำวิธีแก้ error",
    ],
    quickStart: [
      "สมัคร GitHub Copilot ที่ github.com/features/copilot",
      "ติดตั้ง GitHub Copilot extension ใน VS Code",
      "Login กับ GitHub account",
      "เริ่มเขียนโค้ด → ดู suggestion สีเทาๆ → กด Tab รับ",
      "เขียน comment อธิบาย → Enter → Copilot สร้างโค้ดให้",
    ],
    proTips: [
      "เขียน comment ที่ชัดเจนก่อน → Copilot suggest ได้ดีขึ้น",
      "กด Ctrl+Enter ดู suggestion หลายตัวเลือก",
      "ใช้ Copilot Chat (Cmd+I) ถาม/แก้โค้ดในตัว editor",
      "อย่าเชื่อ Copilot 100% ตรวจสอบโค้ดที่ suggest เสมอ",
    ],
    alternatives: ["Cursor AI", "Codeium (free)", "Tabnine", "Amazon CodeWhisperer"],
  },
  {
    name: "ChatGPT / Claude",
    slug: "chatgpt-claude",
    tagline: "AI chatbot ที่ dev ใช้ทุกวันเพื่อ debug, เรียนรู้, สร้างโค้ด",
    description: "ChatGPT (OpenAI) และ Claude (Anthropic) เป็น AI chatbot ที่ developer ใช้ในชีวิตประจำวัน — อธิบายโค้ด, debug, สร้าง regex, เขียน SQL, แปลง data, brainstorm solution",
    icon: "💬",
    category: "ai",
    pricing: "freemium",
    platforms: ["Web", "iOS", "Android", "API"],
    url: "https://chat.openai.com",
    whyUse: [
      "อธิบายโค้ดหรือ concept ที่ไม่เข้าใจ — เหมือนมี senior dev ถามได้ตลอด",
      "Debug error — paste error message แล้วได้คำแนะนำทันที",
      "สร้าง regex, SQL query, config file ที่ซับซ้อน",
      "Brainstorm architecture, naming, approach",
      "แปลง data format เช่น CSV→JSON, XML→YAML",
    ],
    keyFeatures: [
      "Code Generation — สร้างโค้ดจากคำอธิบาย",
      "Code Explanation — อธิบายโค้ดที่ไม่เข้าใจ",
      "Debugging — หา bug จาก error message + code",
      "Learning — สอน concept ใหม่ พร้อมตัวอย่าง",
      "Writing — เขียน docs, commit message, PR description",
      "Translation — แปลงภาษาโปรแกรม Python→JS, SQL→ORM",
    ],
    quickStart: [
      "สมัครที่ chat.openai.com หรือ claude.ai",
      "ลองถาม: \"อธิบาย async/await ใน JavaScript แบบง่ายๆ\"",
      "ลอง debug: paste error + โค้ด → ถาม \"ทำไม error?\"",
      "ลอง generate: \"สร้าง Express API สำหรับ CRUD users\"",
      "ลอง explain: paste โค้ด → \"อธิบายโค้ดนี้\"",
    ],
    proTips: [
      "ให้ context มากที่สุด: ภาษา, framework, เวอร์ชัน, error ทั้งหมด",
      "ใช้ System Prompt: \"คุณเป็น senior dev ที่เชี่ยวชาญ Next.js + TypeScript\"",
      "ถามเป็นขั้นตอน: 1) อธิบาย concept → 2) ดูตัวอย่าง → 3) ลองเอง",
      "อย่าเชื่อ 100% — verify โค้ดที่ AI สร้างเสมอ",
    ],
    alternatives: ["Gemini (Google)", "Perplexity", "Phind"],
  },

  // ─── PRODUCTIVITY ───
  {
    name: "Raycast / Alfred",
    slug: "raycast",
    tagline: "Launcher + Productivity ที่ dev ต้องมี (macOS)",
    description: "Raycast (หรือ Alfred) เป็น app launcher ที่ทำได้มากกว่าแค่เปิดแอป — ค้นหาไฟล์, snippet, clipboard history, window management, calculator, รัน script ได้หมด",
    icon: "🚀",
    category: "productivity",
    pricing: "freemium",
    platforms: ["macOS"],
    url: "https://www.raycast.com",
    whyUse: [
      "เปิดแอป, ค้นไฟล์, ค้น Google เร็วกว่า Spotlight",
      "Clipboard History — ดู/ค้นหาทุกอย่างที่เคย copy",
      "Snippets — พิมพ์ ;email → แทนด้วย email จริง",
      "Window Management — จัด window โดยไม่ต้องติดตั้งแอปเพิ่ม",
      "Extensions — GitHub, Jira, Docker, npm ค้นได้จาก Raycast",
    ],
    keyFeatures: [
      "App Launcher — เปิดแอปด้วยการพิมพ์ชื่อ",
      "File Search — ค้นไฟล์เร็วกว่า Finder",
      "Clipboard History — ย้อนดูทุกอย่างที่เคย copy",
      "Snippets — text expansion อัตโนมัติ",
      "Calculator — คำนวณ, แปลงหน่วย, timezone",
      "Extensions Store — เพิ่ม tool เฉพาะ dev",
      "AI — ถาม AI ได้ทันทีจาก launcher",
    ],
    quickStart: [
      "ดาวน์โหลดจาก raycast.com",
      "ตั้ง hotkey แทน Spotlight: Cmd+Space",
      "ลองพิมพ์ชื่อแอป → Enter เปิดทันที",
      "ติดตั้ง Extensions: GitHub, Docker, Tailwind CSS",
      "ตั้ง Clipboard History hotkey: Cmd+Shift+V",
    ],
    proTips: [
      "ใช้ Quicklinks: พิมพ์ 'gh' → เปิด GitHub repo ของโปรเจกต์",
      "สร้าง Snippet สำหรับ code template ที่ใช้บ่อย",
      "ตั้ง Floating Notes สำหรับจด TODO ระหว่างวัน",
      "ใช้ Confetti extension ฉลองเวลา deploy สำเร็จ 🎉",
    ],
    alternatives: ["Alfred", "Spotlight (built-in)", "Wox (Windows)"],
  },

  // ─── MONITORING & LOGGING ───
  {
    name: "Sentry",
    slug: "sentry",
    tagline: "จับ error ใน production แบบ real-time",
    description: "Sentry คือ error tracking platform — จับ error ที่เกิดใน production อัตโนมัติ แสดง stack trace, user context, breadcrumb ช่วยหาสาเหตุและแก้บัก ได้เร็วมาก",
    icon: "🐛",
    category: "monitoring",
    pricing: "freemium",
    platforms: ["Web"],
    url: "https://sentry.io",
    whyUse: [
      "จับ error อัตโนมัติ ไม่ต้องรอ user report",
      "Stack trace + source map ดูว่า error เกิดที่บรรทัดไหน",
      "Context — ดูว่า user ทำอะไรก่อน error (breadcrumb)",
      "แจ้งเตือนทาง Slack/email เมื่อเกิด error ใหม่",
      "Performance monitoring — ดู slow transactions",
    ],
    keyFeatures: [
      "Error Tracking — จับ unhandled errors อัตโนมัติ",
      "Stack Traces — ดูบรรทัดที่ error + source maps",
      "Breadcrumbs — ลำดับเหตุการณ์ก่อนเกิด error",
      "Release Tracking — ดูว่า error เกิดใน version ไหน",
      "Performance — ดู slow API, slow page loads",
      "Alerts — แจ้งเตือน Slack/email เมื่อ error spike",
    ],
    quickStart: [
      "สมัครที่ sentry.io (ฟรี 5,000 errors/เดือน)",
      "สร้าง project: เลือก platform (Next.js, React, Node.js)",
      "ติดตั้ง SDK: npm install @sentry/nextjs",
      "ตั้งค่า DSN ใน sentry.client.config.ts",
      "Deploy แล้วลอง throw error → ดูใน Sentry dashboard",
    ],
    proTips: [
      "อัปโหลด source maps ให้ Sentry ดู code จริงได้",
      "ตั้ง environment แยก: dev, staging, production",
      "ใช้ Sentry.captureMessage() จับ error ที่ handle เองด้วย",
      "ตั้ง Alert rules: error ใหม่ > 5 ครั้ง/นาที → แจ้ง Slack",
    ],
    alternatives: ["Bugsnag", "LogRocket", "Datadog", "New Relic"],
  },
  {
    name: "Vercel Analytics",
    slug: "vercel-analytics",
    tagline: "วิเคราะห์ performance เว็บ Next.js แบบง่ายๆ",
    description: "Vercel Analytics (Web Analytics + Speed Insights) ให้ดูจำนวนผู้เข้าชม, Core Web Vitals, page load time ของเว็บ Next.js ที่ deploy บน Vercel — ตั้งค่าง่ายมากแค่ไม่กี่บรรทัด",
    icon: "📈",
    category: "monitoring",
    pricing: "freemium",
    platforms: ["Web (Vercel)"],
    url: "https://vercel.com/analytics",
    whyUse: [
      "ดู traffic, page views, visitors แบบ real-time",
      "Core Web Vitals — LCP, FID, CLS ดูง่าย",
      "Speed Insights — ดูว่าหน้าไหนโหลดช้า",
      "ไม่ต้อง setup อะไรมาก ใช้กับ Vercel ได้เลย",
    ],
    keyFeatures: [
      "Web Analytics — visitors, page views, referrers",
      "Speed Insights — Core Web Vitals per page",
      "Real User Monitoring — data จาก user จริงๆ",
      "Privacy-friendly — ไม่ใช้ cookies",
    ],
    quickStart: [
      "npm install @vercel/analytics @vercel/speed-insights",
      "เพิ่ม <Analytics /> ใน layout.tsx",
      "เพิ่ม <SpeedInsights /> ใน layout.tsx",
      "Deploy ไป Vercel → เปิด Analytics tab ใน dashboard",
    ],
    proTips: [
      "ดู Speed Insights ทุกสัปดาห์ หา page ที่ต้อง optimize",
      "เปรียบเทียบ CWV ก่อน-หลัง optimization",
      "ใช้ร่วมกับ Google Search Console ดู SEO impact",
    ],
    alternatives: ["Google Analytics", "Plausible", "Fathom", "PostHog"],
  },

  // ─── DOCUMENTATION ───
  {
    name: "Storybook",
    slug: "storybook",
    tagline: "พัฒนาและ document UI components แบบ isolated",
    description: "Storybook ให้สร้างและทดสอบ UI components แยกจากแอป — ดู component ในทุก state, ทำเป็น living documentation ให้ทีม, ทดสอบ visual regression",
    icon: "📖",
    category: "docs",
    pricing: "open-source",
    platforms: ["Web (localhost)"],
    url: "https://storybook.js.org",
    whyUse: [
      "พัฒนา component แยก ไม่ต้องเปิดทั้งแอป",
      "ดู component ในทุก state: loading, error, empty, full",
      "Documentation อัตโนมัติจาก props/types",
      "Visual testing — จับ UI ที่เปลี่ยนโดยไม่ตั้งใจ",
      "Designer + Dev ใช้ดู component catalog ร่วมกัน",
    ],
    keyFeatures: [
      "Stories — แสดง component ในแต่ละ state",
      "Controls — ปรับ props แบบ interactive",
      "Docs — auto-generated documentation",
      "Addons — accessibility, viewport, design tokens",
      "Visual Testing — Chromatic integration",
      "MDX Support — เขียน docs + code ในไฟล์เดียว",
    ],
    quickStart: [
      "npx storybook@latest init (ในโปรเจกต์ React/Next.js)",
      "npm run storybook → เปิดที่ localhost:6006",
      "สร้าง story: Button.stories.tsx",
      "export default { component: Button }",
      "export const Primary = { args: { label: 'Click me' } }",
    ],
    proTips: [
      "เขียน story สำหรับทุก state: default, hover, disabled, loading, error",
      "ใช้ Chromatic สำหรับ visual regression testing ใน CI",
      "ใช้ addon-a11y ตรวจ accessibility ของทุก component",
      "สร้าง design system documentation ด้วย Storybook + MDX",
    ],
    alternatives: ["Docusaurus", "Ladle", "Histoire (Vue)"],
  },

  // ─── TESTING & QA ───
  {
    name: "Playwright",
    slug: "playwright",
    tagline: "E2E testing ที่เร็ว เสถียร รองรับทุก browser",
    description: "Playwright จาก Microsoft เป็น framework สำหรับ End-to-End testing — ควบคุม Chrome, Firefox, Safari ทดสอบเว็บเหมือนผู้ใช้จริง auto-wait, trace viewer, screenshot comparison ครบ",
    icon: "🎭",
    category: "testing",
    pricing: "open-source",
    platforms: ["Windows", "macOS", "Linux"],
    url: "https://playwright.dev",
    whyUse: [
      "รองรับทุก browser: Chromium, Firefox, WebKit (Safari)",
      "Auto-wait — รอ element พร้อมก่อน interact อัตโนมัติ",
      "เร็วและเสถียร — ลด flaky tests ได้มาก",
      "Trace Viewer — ดู screenshot + DOM snapshot ทุก step",
      "Codegen — record action แล้วสร้าง test code ให้",
    ],
    keyFeatures: [
      "Cross-browser — Chrome, Firefox, Safari ใน test เดียวกัน",
      "Auto-waiting — ไม่ต้องเขียน sleep() หรือ waitFor()",
      "Codegen — เปิดเบราว์เซอร์ คลิก → สร้าง test code",
      "Trace Viewer — debug test ด้วย timeline + screenshots",
      "API Testing — ทดสอบ API ร่วมกับ UI test",
      "Visual Comparison — เปรียบเทียบ screenshot",
      "Parallel Testing — รัน test พร้อมกันหลาย browser",
    ],
    quickStart: [
      "npm init playwright@latest",
      "เขียน test: test('homepage', async ({ page }) => { ... })",
      "รัน: npx playwright test",
      "ดูผล: npx playwright show-report",
      "สร้าง test ด้วย codegen: npx playwright codegen localhost:3000",
    ],
    proTips: [
      "ใช้ codegen สร้าง test เร็ว แล้วค่อย refactor ทีหลัง",
      "ใช้ trace: 'on-first-retry' เพื่อ debug test ที่ fail",
      "สร้าง Page Object Model สำหรับ reusable page interactions",
      "รันใน CI ด้วย GitHub Actions: npx playwright install --with-deps",
    ],
    alternatives: ["Cypress", "Selenium", "Puppeteer", "TestCafe"],
  },
  {
    name: "Jest / Vitest",
    slug: "jest-vitest",
    tagline: "Unit & Integration testing สำหรับ JavaScript",
    description: "Jest (Facebook) และ Vitest (Vite ecosystem) เป็น test framework หลักของ JS/TS — เขียน unit test, mock, snapshot, coverage ครบ Vitest เร็วกว่าเพราะใช้ Vite",
    icon: "🃏",
    category: "testing",
    pricing: "open-source",
    platforms: ["Windows", "macOS", "Linux"],
    url: "https://jestjs.io",
    whyUse: [
      "เขียน test ง่ายด้วย describe/it/expect",
      "Mocking — จำลอง API, module, timer ได้หมด",
      "Snapshot testing — จับการเปลี่ยนแปลงของ UI",
      "Code Coverage — ดูว่าโค้ดถูก test กี่ %",
      "Watch mode — รัน test อัตโนมัติเมื่อแก้โค้ด",
    ],
    keyFeatures: [
      "expect() assertions — toBe, toEqual, toThrow, toHaveBeenCalled",
      "Mock functions — jest.fn(), jest.mock(), jest.spyOn()",
      "Snapshot testing — toMatchSnapshot()",
      "Code Coverage — --coverage flag",
      "Watch Mode — --watch รัน test ที่เกี่ยวข้องกับไฟล์ที่แก้",
      "Parallel — รัน test files พร้อมกัน",
    ],
    quickStart: [
      "Jest: npm install -D jest @types/jest ts-jest",
      "Vitest: npm install -D vitest",
      "สร้างไฟล์ sum.test.ts",
      "เขียน: test('1 + 2 = 3', () => expect(add(1,2)).toBe(3))",
      "รัน: npx jest หรือ npx vitest",
    ],
    proTips: [
      "ใช้ Vitest ถ้าโปรเจกต์ใช้ Vite — เร็วกว่า Jest มาก",
      "ใช้ --watch mode ระหว่าง develop — ได้ feedback ทันที",
      "Mock เฉพาะที่จำเป็น อย่า mock ทุกอย่าง",
      "ตั้ง coverage threshold ใน config: branches: 80, functions: 80",
    ],
    alternatives: ["Mocha", "AVA", "uvu"],
  },
];

export function searchTools(query: string): DevTool[] {
  if (!query.trim()) return tools;
  const q = query.toLowerCase();
  return tools.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.tagline.includes(q) ||
      t.description.includes(q) ||
      t.category.includes(q) ||
      t.keyFeatures.some((f) => f.toLowerCase().includes(q)),
  );
}

export function getToolsByCategory(category: string): DevTool[] {
  return tools.filter((t) => t.category === category);
}

export function getToolBySlug(slug: string): DevTool | undefined {
  return tools.find((t) => t.slug === slug);
}
